19 render inputtasks in box task
GSG-FC03/Todolist-Team1 pull request #25
Opened 2021-07-17 17:20 UTC by FatmaHossam5

2021-07-17 18:11 UTC, MohammedHasan-99 requested changes

2021-07-17 18:11 UTC, MohammedHasan-99 commented on script/main.js
> +    let due = document.createTextNode(element.due_time);
make due as input type instead:
- let due = document.createElement("input");
- due.type = "datetime-local";
- due.value = element.due_time;
- due.readOnly = true;

2021-07-17 18:11 UTC, MohammedHasan-99 commented on script/main.js
> +    console.log(element);
delete this line :3

2021-07-17 18:11 UTC, MohammedHasan-99 commented on css/home.css
> -  background-color: white;
why did you remove this?

2021-07-17 19:16 UTC, MohammedHasan-99 approved these changes

2021-07-17 20:23 UTC, MMansour87 requested changes
Where the is the task id `<lable>` element in the right section of the task
we need to create it and assign its content with id value in local storage array
I need to refer to the array

2021-07-18 08:11 UTC, Doaa-Abdulsalam approved these changes

2021-07-18 08:21 UTC, MMansour87 approved these changes
I will do the id <lable> as it related to my issue

2021-07-18 08:21 UTC, merged